// ═══════════════════════════════════════════════════════════════════
// MARKETING INTELLIGENCE v2 — Full Implementation Brief Build
// Priorities 1–13 implemented
// ═══════════════════════════════════════════════════════════════════

import { useState, useRef, useEffect } from "react";
import { Camera, Sparkles, Calendar, Copy, ExternalLink, Eye, Trash2, ChevronLeft, Clock, Image as ImageIcon, Type, LayoutTemplate, RefreshCw, Check, X, Plus, Megaphone, ArrowRight, Edit3, Layers, Wand2, LogOut, Store, Upload, Zap, Shuffle, AlertCircle } from "lucide-react";

// ─── THEME ──────────────────────────────────────────────────────
const C={bg:"#060A13",card:"#0D1420",surface:"#111927",border:"#1A2540",borderLight:"#243352",text:"#F1F5F9",white:"#FFFFFF",muted:"#8494B2",dim:"#4A5A7A",amber:"#F59E0B",amberDim:"rgba(245,158,11,0.12)",green:"#10B981",greenDim:"rgba(16,185,129,0.12)",blue:"#3B6FD4",blueDim:"rgba(59,111,212,0.12)",red:"#EF4444",redDim:"rgba(239,68,68,0.12)",purple:"#A855F7",purpleDim:"rgba(168,85,247,0.12)",purpleGlow:"rgba(168,85,247,0.25)"};
const FONT="'DM Sans',-apple-system,BlinkMacSystemFont,sans-serif";
const DISPLAY="'Fraunces',Georgia,serif";

// ─── CAPTION STYLES (Section 3.1 — replaces old TONES) ─────────
const CAPTION_STYLES=[
  {id:"hype_drop",label:"Hype Drop",emoji:"🔥",desc:"Viral energy, FOMO, urgency",best:"Trending items"},
  {id:"new_arrival",label:"New Arrival",emoji:"👀",desc:"Just landed, curiosity-led",best:"New stock"},
  {id:"price_hero",label:"Price Hero",emoji:"💰",desc:"Lead with the price",best:"Deals & offers"},
  {id:"local_shoutout",label:"Local Shoutout",emoji:"📍",desc:"Community feel, warm",best:"Regulars"},
  {id:"weekend_vibe",label:"Weekend Vibe",emoji:"🍻",desc:"Relaxed, lifestyle",best:"Fri/Sat posts"},
  {id:"staff_pick",label:"Staff Pick",emoji:"⭐",desc:"Personal recommendation",best:"Differentiation"},
];

// ─── TEMPLATES (Section 4.2 — renamed with identities) ─────────
function getSeasonalTemplate(){const m=new Date().getMonth();if(m===2||m===3)return{id:"seasonal",name:"Easter",bg:"#FEF3C7",accent:"#F59E0B",badge:"🐣 Easter Deals",textColor:"#1E293B",style:"light"};if(m>=5&&m<=7)return{id:"seasonal",name:"Summer",bg:"#ECFDF5",accent:"#10B981",badge:"☀️ Summer Vibes",textColor:"#064E3B",style:"light"};if(m===10||m===11)return{id:"seasonal",name:"Christmas",bg:"#0F172A",accent:"#EF4444",badge:"🎄 Festive Deals",textColor:"#FFFFFF",style:"dark"};return{id:"seasonal",name:"In Store Now",bg:"#FFF7ED",accent:"#F97316",badge:"🛒 In Store Now",textColor:"#1E293B",style:"light"};}
const TEMPLATES=[
  {id:"new_in_store",name:"New In Store",bg:"#FAFAF9",accent:"#16A34A",badge:"NEW IN",textColor:"#1E293B",style:"light"},
  {id:"deal_alert",name:"Deal Alert",bg:"#0F172A",accent:"#EF4444",badge:"DEAL",textColor:"#FFFFFF",style:"dark"},
  {id:"weekend_vibes",name:"Weekend Vibes",bg:"#1C1917",accent:"#F59E0B",badge:null,textColor:"#FAFAF9",style:"dark"},
  {id:"staff_pick",name:"Staff Pick",bg:"#FFFBEB",accent:"#D97706",badge:"⭐ Staff Pick",textColor:"#1E293B",style:"light"},
  {id:"viral_drop",name:"Viral Drop",bg:"#09090B",accent:"#A855F7",badge:"🔥 DROP",textColor:"#FFFFFF",style:"dark"},
  getSeasonalTemplate(),
];

// ─── SMART DAILY PROMPT (Section 6) ─────────────────────────────
function getTodayPrompt(){const day=new Date().getDay(),month=new Date().getMonth(),date=new Date().getDate();if((month===2&&date>=25)||(month===3&&date<=21))return{emoji:"🐣",text:"Easter is coming — push chocolate, eggs and seasonal treats today.",style:"hype_drop",template:"seasonal"};if(month===11&&date>=18)return{emoji:"🎄",text:"Christmas week — stock up posts for festive drinks, snacks and gifts.",style:"hype_drop",template:"seasonal"};const D={0:{emoji:"🛒",text:"Sunday — your customers are prepping for the week. Push meal deals and essentials.",style:"price_hero"},1:{emoji:"☀️",text:"New week, fresh stock. A great day to post a new arrival or staff pick.",style:"new_arrival"},2:{emoji:"🍫",text:"Tuesday slump — snacks and treats are your best posts today.",style:"staff_pick"},3:{emoji:"💰",text:"Mid-week — deal posts and price-hero content work well on Wednesdays.",style:"price_hero"},4:{emoji:"⚡",text:"Thursday — people are thinking about the weekend. Push drinks and snacks.",style:"weekend_vibe"},5:{emoji:"🍺",text:"Friday — drinks, crisps and weekend treats. Your highest engagement day.",style:"weekend_vibe"},6:{emoji:"☀️",text:"Saturday — catch the weekend shoppers. A product display or new arrival works great.",style:"new_arrival"}};return D[day];}

// ─── AUTO-SCHEDULE (Section 5.2) ────────────────────────────────
const PREFERRED_DAYS=[0,2,4,5,1,3,6];
const POSTING_TIMES={0:"9:00am",1:"12:00pm",2:"9:00am",3:"6:00pm",4:"9:00am",5:"11:00am",6:"5:00pm"};
function autoSchedule(posts,existing={}){const sched={};const already=new Set(Object.values(existing).flat());const todo=posts.filter(p=>!already.has(p.id));todo.forEach((p,i)=>{const d=PREFERRED_DAYS[i%7];sched[d]=[...(sched[d]||[]),p.id];});const merged={...existing};Object.keys(sched).forEach(k=>{merged[k]=[...(merged[k]||[]),...sched[k]];});return merged;}

// ─── IMAGE ENHANCEMENT (Section 8) ─────────────────────────────
function enhanceImage(src,price,storeName,tmpl){return new Promise(resolve=>{const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d"),img=new Image();img.onload=()=>{const size=Math.min(img.width,img.height);canvas.width=1080;canvas.height=1080;ctx.filter="brightness(1.08) contrast(1.12) saturate(1.05)";ctx.drawImage(img,(img.width-size)/2,(img.height-size)/2,size,size,0,0,1080,1080);ctx.filter="none";if(price){const bw=180,bh=70,bx=880,by=980;ctx.fillStyle=tmpl?.accent||"#F59E0B";ctx.beginPath();ctx.roundRect(bx,by,bw,bh,14);ctx.fill();ctx.fillStyle=tmpl?.style==="light"?"#fff":"#000";ctx.font="bold 34px Arial";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("£"+price,bx+bw/2,by+bh/2);}if(storeName){ctx.fillStyle="rgba(255,255,255,0.35)";ctx.font="600 22px Arial";ctx.textAlign="left";ctx.textBaseline="bottom";ctx.fillText(storeName,24,1058);}resolve(canvas.toDataURL("image/jpeg",0.92));};img.src=src;});}

const DAYS_SHORT=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const DAYS_FULL=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];

// ═══ SHARED UI ══════════════════════════════════════════════════
function Card({children,style,onClick,className}){return<div onClick={onClick} className={className} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:16,padding:20,transition:"border-color 0.25s",...style}}>{children}</div>;}
function Badge({children,color=C.purple,style}){return<span style={{display:"inline-flex",alignItems:"center",gap:5,fontSize:10,fontWeight:700,letterSpacing:"0.06em",textTransform:"uppercase",padding:"4px 10px",borderRadius:8,background:`${color}18`,color,...style}}>{children}</span>;}
function Btn({children,primary,small,disabled,onClick,style}){const base={display:"inline-flex",alignItems:"center",gap:6,padding:small?"8px 14px":"12px 20px",borderRadius:10,border:"none",cursor:disabled?"default":"pointer",fontSize:small?12:13,fontWeight:700,fontFamily:FONT,transition:"all 0.2s ease",opacity:disabled?0.45:1};const v=primary?{background:C.purple,color:"#fff",boxShadow:`0 0 20px ${C.purpleGlow}`}:{background:C.surface,color:C.muted,border:`1px solid ${C.border}`};return<button onClick={disabled?undefined:onClick} style={{...base,...v,...style}}>{children}</button>;}
function SectionLabel({children,icon,style}){return<div style={{fontSize:10,fontWeight:700,color:C.dim,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:10,display:"flex",alignItems:"center",gap:6,...style}}>{icon} {children}</div>;}
function Toggle({value,onChange,label}){return<div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"8px 0"}}><span style={{fontSize:13,color:C.muted}}>{label}</span><button onClick={()=>onChange(!value)} style={{width:44,height:24,borderRadius:12,border:"none",cursor:"pointer",background:value?C.purple:C.border,position:"relative",transition:"background 0.2s"}}><div style={{width:18,height:18,borderRadius:"50%",background:"#fff",position:"absolute",top:3,left:value?23:3,transition:"left 0.2s"}}/></button></div>;}

// ─── TOAST (Section 2.2) ────────────────────────────────────────
function Toast({message,type="success",onDone}){useEffect(()=>{const t=setTimeout(onDone,2500);return()=>clearTimeout(t);},[onDone]);return<div style={{position:"fixed",top:16,left:"50%",transform:"translateX(-50%)",padding:"12px 20px",borderRadius:12,zIndex:9999,background:type==="success"?C.green:C.red,color:"#fff",fontSize:13,fontWeight:700,fontFamily:FONT,boxShadow:"0 8px 30px rgba(0,0,0,0.4)",animation:"fadeUp 0.3s ease",display:"flex",alignItems:"center",gap:8}}>{type==="success"?<Check size={14}/>:<AlertCircle size={14}/>}{message}</div>;}

// ═══ AUTH SCREEN ════════════════════════════════════════════════
function AuthScreen({onAuth}){const[storeName,setStoreName]=useState("");const[error,setError]=useState("");const go=()=>{const n=storeName.trim();if(!n){setError("Enter your store name");return;}localStorage.setItem("mi_store_name",n);onAuth(n);};return<div style={{minHeight:"100vh",background:C.bg,fontFamily:FONT,color:C.text,display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div style={{position:"fixed",top:"-20%",left:"30%",width:400,height:400,background:`radial-gradient(circle,${C.purpleGlow} 0%,transparent 70%)`,pointerEvents:"none",filter:"blur(60px)"}}/><div style={{width:"100%",maxWidth:380,textAlign:"center",position:"relative"}}><div className="fade-up d1" style={{width:72,height:72,borderRadius:20,margin:"0 auto 24px",background:`linear-gradient(135deg,${C.purple},#7C3AED)`,display:"flex",alignItems:"center",justifyContent:"center",boxShadow:`0 0 40px ${C.purpleGlow}`}}><Megaphone size={32} color="#fff" strokeWidth={2.2}/></div><h1 className="fade-up d2" style={{fontFamily:DISPLAY,fontSize:28,fontWeight:800,color:C.white,marginBottom:6}}>Marketing <span style={{color:C.purple}}>Intelligence</span></h1><p className="fade-up d3" style={{fontSize:13,color:C.dim,marginBottom:32,lineHeight:1.6}}>AI-powered social content for your store.<br/>Snap it. Style it. Post it.</p><div className="fade-up d4" style={{background:C.card,borderRadius:16,padding:24,border:`1px solid ${C.border}`,textAlign:"left"}}><div style={{fontSize:12,fontWeight:700,color:C.dim,marginBottom:8,textTransform:"uppercase",letterSpacing:"0.06em"}}>Store Name</div><input value={storeName} onChange={e=>{setStoreName(e.target.value);setError("");}} onKeyDown={e=>e.key==="Enter"&&go()} placeholder="e.g. Londis Horden" autoFocus style={{width:"100%",padding:"14px 16px",borderRadius:12,background:C.surface,color:C.white,border:`1.5px solid ${C.border}`,fontSize:15,outline:"none",fontFamily:FONT,boxSizing:"border-box",marginBottom:12}}/>{error&&<div style={{fontSize:12,color:C.red,marginBottom:10}}>{error}</div>}<button onClick={go} style={{width:"100%",padding:16,borderRadius:12,border:"none",background:storeName.trim()?C.purple:C.surface,color:storeName.trim()?"#fff":C.dim,fontSize:15,fontWeight:700,cursor:"pointer",fontFamily:FONT,transition:"all 0.2s",boxShadow:storeName.trim()?`0 0 30px ${C.purpleGlow}`:"none"}}>Get Started <ArrowRight size={16} style={{verticalAlign:"middle",marginLeft:4}}/></button></div><p className="fade-up d5" style={{fontSize:11,color:C.dim,marginTop:20}}>Part of <span style={{color:C.muted,fontWeight:600}}>Retail Intelligence</span></p></div></div>;}

// ═══ APP SHELL ══════════════════════════════════════════════════
export default function App(){
  const[storeName,setStoreName]=useState(localStorage.getItem("mi_store_name")||"");
  const[view,setView]=useState("hub");
  const[posts,setPosts]=useState(()=>{try{return JSON.parse(localStorage.getItem("mi_posts")||"[]");}catch{return[];}});
  const[schedule,setSchedule]=useState(()=>{try{return JSON.parse(localStorage.getItem("mi_schedule")||"{}");}catch{return{};}});
  const[editingPost,setEditingPost]=useState(null);
  const[toast,setToast]=useState(null);
  const[schedulePrompt,setSchedulePrompt]=useState(null);

  useEffect(()=>{try{localStorage.setItem("mi_posts",JSON.stringify(posts));}catch{setToast({msg:"Save failed — storage full",type:"error"});};},[posts]);
  useEffect(()=>{try{localStorage.setItem("mi_schedule",JSON.stringify(schedule));}catch{setToast({msg:"Schedule save failed",type:"error"});};},[schedule]);

  const showToast=(msg,type="success")=>setToast({msg,type});

  const savePost=(post)=>{try{if(editingPost){setPosts(prev=>prev.map(p=>p.id===post.id?post:p));}else{setPosts(prev=>[post,...prev]);}showToast("Post saved ✅");setSchedulePrompt(post);setEditingPost(null);setView("hub");}catch{showToast("Save failed — try again","error");}};

  const saveBatch=(newPosts,newSched)=>{try{setPosts(prev=>[...newPosts,...prev]);setSchedule(prev=>{const m={...prev};Object.keys(newSched).forEach(k=>{m[k]=[...(m[k]||[]),...newSched[k]];});return m;});showToast(`${newPosts.length} posts saved & scheduled ✅`);setView("hub");}catch{showToast("Save failed","error");}};

  if(!storeName)return<AuthScreen onAuth={setStoreName}/>;

  return<>
    {toast&&<Toast message={toast.msg} type={toast.type} onDone={()=>setToast(null)}/>}
    {schedulePrompt&&view==="hub"&&<SchedulePromptModal post={schedulePrompt} onAssign={d=>{setSchedule(prev=>({...prev,[d]:[...(prev[d]||[]),schedulePrompt.id]}));showToast(`Added to ${DAYS_FULL[d]} ✅`);setSchedulePrompt(null);}} onDismiss={()=>setSchedulePrompt(null)}/>}
    {view==="hub"&&<HubView storeName={storeName} posts={posts} schedule={schedule} onCreateNew={()=>{setEditingPost(null);setView("create");}} onBatch={()=>setView("batch")} onEdit={p=>{setEditingPost(p);setView("create");}} onSchedule={()=>setView("schedule")} onDelete={id=>{setPosts(prev=>prev.filter(p=>p.id!==id));setSchedule(prev=>{const n={...prev};Object.keys(n).forEach(k=>{n[k]=n[k].filter(pid=>pid!==id);});return n;});showToast("Post deleted");}} onLogout={()=>{localStorage.removeItem("mi_store_name");setStoreName("");}}/>}
    {view==="create"&&<CreateView post={editingPost} storeName={storeName} onSave={savePost} onBack={()=>{setEditingPost(null);setView("hub");}}/>}
    {view==="batch"&&<BatchView storeName={storeName} onSave={saveBatch} onBack={()=>setView("hub")}/>}
    {view==="schedule"&&<ScheduleView posts={posts} schedule={schedule} onUpdate={setSchedule} onBack={()=>setView("hub")} showToast={showToast}/>}
  </>;
}

// ═══ SCHEDULE PROMPT MODAL (Section 2.2) ════════════════════════
function SchedulePromptModal({post,onAssign,onDismiss}){const today=new Date().getDay();const sug=PREFERRED_DAYS.find(d=>d>=(today===0?6:today-1))??0;return<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.6)",zIndex:9000,display:"flex",alignItems:"center",justifyContent:"center",padding:20,backdropFilter:"blur(4px)"}}><div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:20,padding:24,maxWidth:340,width:"100%",textAlign:"center",fontFamily:FONT}}><div style={{fontSize:15,fontWeight:700,color:C.white,marginBottom:6}}>Add to this week's schedule?</div><div style={{fontSize:12,color:C.dim,marginBottom:16}}>We suggest <strong style={{color:C.purple}}>{DAYS_FULL[sug]}</strong> at {POSTING_TIMES[sug]}</div><div style={{display:"flex",flexWrap:"wrap",gap:6,justifyContent:"center",marginBottom:16}}>{DAYS_SHORT.map((d,i)=><button key={d} onClick={()=>onAssign(i)} style={{padding:"8px 14px",borderRadius:8,border:i===sug?`2px solid ${C.purple}`:`1px solid ${C.border}`,background:i===sug?C.purpleDim:C.surface,color:i===sug?C.purple:C.muted,fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:FONT}}>{d}</button>)}</div><button onClick={onDismiss} style={{background:"none",border:"none",color:C.dim,fontSize:12,cursor:"pointer",fontFamily:FONT}}>Skip for now</button></div></div>;}

// ═══ HUB VIEW (Section 9 — redesigned) ═════════════════════════
function HubView({storeName,posts,schedule,onCreateNew,onBatch,onEdit,onSchedule,onDelete,onLogout}){
  const sIds=Object.values(schedule).flat();const unsch=posts.filter(p=>!sIds.includes(p.id));const tp=getTodayPrompt();
  return<div style={{minHeight:"100vh",background:C.bg,fontFamily:FONT,color:C.text}}>
    <div style={{padding:"16px 20px",borderBottom:`1px solid ${C.border}`,background:`linear-gradient(180deg,${C.card} 0%,${C.bg} 100%)`,display:"flex",alignItems:"center",justifyContent:"space-between"}}>
      <div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:36,height:36,borderRadius:10,background:`linear-gradient(135deg,${C.purple},#7C3AED)`,display:"flex",alignItems:"center",justifyContent:"center"}}><Megaphone size={18} color="#fff"/></div><div><div style={{fontSize:16,fontWeight:800,color:C.white,fontFamily:DISPLAY}}>Marketing <span style={{color:C.purple}}>Intelligence</span></div><div style={{fontSize:11,color:C.dim,display:"flex",alignItems:"center",gap:4}}><Store size={10}/> {storeName}</div></div></div>
      <button onClick={onLogout} style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:8,padding:"6px 10px",color:C.dim,cursor:"pointer",display:"flex",alignItems:"center",gap:4,fontSize:11,fontWeight:600,fontFamily:FONT}}><LogOut size={12}/> Sign Out</button>
    </div>
    <div style={{padding:20,maxWidth:540,margin:"0 auto"}}>
      {/* Smart Daily Prompt */}
      <Card className="fade-up d1" style={{marginBottom:16,background:`linear-gradient(135deg,${C.card},${C.surface})`,border:`1px solid ${C.purple}33`}}>
        <SectionLabel icon={<Calendar size={11} color={C.purple}/>}>What to post today</SectionLabel>
        <div style={{display:"flex",alignItems:"flex-start",gap:12,marginBottom:12}}><span style={{fontSize:28}}>{tp.emoji}</span><p style={{fontSize:13,color:C.text,lineHeight:1.6,margin:0}}>{tp.text}</p></div>
        <Btn small primary onClick={onCreateNew} style={{borderRadius:8}}>Post something today <ArrowRight size={12}/></Btn>
      </Card>
      {/* CTAs */}
      <div className="fade-up d2" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:20}}>
        <Btn primary onClick={onBatch} style={{justifyContent:"center",padding:16,borderRadius:14,fontSize:13}}><Sparkles size={15}/> Plan My Week</Btn>
        <Btn onClick={onCreateNew} style={{justifyContent:"center",padding:16,borderRadius:14}}><Camera size={15}/> Create One Post</Btn>
      </div>
      {/* Stats */}
      <div className="fade-up d3" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginBottom:20}}>
        {[{l:"Created",v:posts.length,c:C.purple,i:<Layers size={15}/>},{l:"Scheduled",v:sIds.length,c:C.green,i:<Calendar size={15}/>},{l:"Ready",v:unsch.length,c:C.amber,i:<Clock size={15}/>}].map(s=><Card key={s.l} style={{padding:14,textAlign:"center"}}><div style={{color:s.c,marginBottom:6}}>{s.i}</div><div style={{fontSize:24,fontWeight:800,color:C.white,fontFamily:DISPLAY}}>{s.v}</div><div style={{fontSize:9,color:C.dim,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.08em",marginTop:2}}>{s.l}</div></Card>)}
      </div>
      {/* Week */}
      <Card className="fade-up d4" style={{marginBottom:20,cursor:"pointer"}} onClick={onSchedule}>
        <SectionLabel icon={<Calendar size={11} color={C.purple}/>}>This Week</SectionLabel>
        <div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:6}}>
          {DAYS_SHORT.map((d,i)=>{const dp=(schedule[i]||[]).map(id=>posts.find(p=>p.id===id)).filter(Boolean);const has=dp.length>0;return<div key={d} style={{textAlign:"center"}}><div style={{fontSize:9,fontWeight:700,color:C.dim,marginBottom:5,letterSpacing:"0.05em"}}>{d}</div><div style={{width:38,height:38,borderRadius:10,margin:"0 auto",background:has?C.purpleDim:C.surface,border:`1.5px solid ${has?C.purple+"55":C.border}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:800,color:has?C.purple:C.dim}}>{has?dp.length:"—"}</div><div style={{fontSize:8,color:C.dim,marginTop:3}}>{POSTING_TIMES[i]}</div></div>;})}
        </div>
      </Card>
      {/* Posts */}
      {posts.length>0&&<Card className="fade-up d5"><SectionLabel icon={<Layers size={11} color={C.blue}/>}>Your Posts</SectionLabel><div style={{display:"flex",flexDirection:"column",gap:8}}>{posts.map(p=><PostCard key={p.id} post={p} isScheduled={sIds.includes(p.id)} onEdit={()=>onEdit(p)} onDelete={()=>onDelete(p.id)}/>)}</div></Card>}
      {/* Empty */}
      {posts.length===0&&<Card className="fade-up d5" style={{textAlign:"center",padding:48}}><div style={{fontSize:48,marginBottom:16}}>📸</div><div style={{fontSize:17,fontWeight:800,color:C.white,marginBottom:8,fontFamily:DISPLAY}}>Your week starts here</div><div style={{fontSize:13,color:C.dim,marginBottom:20,lineHeight:1.7,maxWidth:300,margin:"0 auto 20px"}}>Upload your products and we'll have your whole week sorted in minutes. No marketing team needed. No thinking required. Just approve and go.</div><Btn primary onClick={onBatch} style={{marginBottom:10}}><Sparkles size={14}/> Plan My Week</Btn><div><button onClick={onCreateNew} style={{background:"none",border:"none",color:C.purple,fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:FONT}}>Or create a single post</button></div></Card>}
      <div style={{textAlign:"center",padding:"32px 0 20px",fontSize:11,color:C.dim}}>Part of <span style={{fontWeight:600,color:C.muted}}>Retail Intelligence</span> · Built in the UK</div>
    </div>
  </div>;
}

// ═══ POST CARD ══════════════════════════════════════════════════
function PostCard({post,isScheduled,onEdit,onDelete}){const[copied,setCopied]=useState(false);const cc=e=>{e.stopPropagation();navigator.clipboard.writeText(post.caption).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),2000);});};return<div style={{background:C.surface,borderRadius:12,overflow:"hidden",border:`1px solid ${C.border}`}}><div style={{display:"flex",gap:12,padding:12}}>{post.imageUrl&&<div style={{width:56,height:56,borderRadius:8,overflow:"hidden",flexShrink:0,background:C.card}}><img src={post.imageUrl} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/></div>}<div style={{flex:1,minWidth:0}}><div style={{fontSize:13,fontWeight:700,color:C.white,marginBottom:3}}>{post.productName||"Untitled"}</div><div style={{fontSize:11,color:C.dim,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",marginBottom:5}}>{post.caption?.slice(0,70)}…</div><div style={{display:"flex",gap:4,flexWrap:"wrap"}}><Badge color={C.purple} style={{fontSize:8,padding:"2px 7px"}}>{post.template?.name||"Classic"}</Badge><Badge color={C.green} style={{fontSize:8,padding:"2px 7px"}}>{CAPTION_STYLES.find(s=>s.id===post.style)?.label||post.style}</Badge>{isScheduled&&<Badge color={C.blue} style={{fontSize:8,padding:"2px 7px"}}>Scheduled</Badge>}</div></div></div><div style={{display:"flex",borderTop:`1px solid ${C.border}`}}>{[{icon:<Edit3 size={11}/>,label:"Edit",fn:onEdit,color:C.blue},{icon:copied?<Check size={11}/>:<Copy size={11}/>,label:copied?"Copied!":"Copy",fn:cc,color:C.green},{icon:<ExternalLink size={11}/>,label:"Facebook",fn:()=>{navigator.clipboard.writeText(post.caption);setTimeout(()=>window.open("https://www.facebook.com","_blank"),300);},color:C.blue},{icon:<Trash2 size={11}/>,label:"Delete",fn:e=>{e.stopPropagation();onDelete();},color:C.red}].map((a,idx)=><button key={a.label} onClick={a.fn} style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",gap:4,padding:"10px 0",background:"none",border:"none",borderRight:idx<3?`1px solid ${C.border}`:"none",color:a.color,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:FONT}}>{a.icon} {a.label}</button>)}</div></div>;}

// ═══ TEMPLATE PREVIEW ═══════════════════════════════════════════
function TemplatePreview({imageUrl,productName,price,template,storeName,size="medium"}){const h=size==="tile"?50:size==="small"?140:size==="large"?380:260;const isTile=size==="tile";return<div style={{background:template.bg,padding:isTile?6:16,position:"relative",overflow:"hidden"}}>{template.badge&&!isTile&&<div style={{position:"absolute",top:12,left:12,zIndex:2,padding:"4px 10px",borderRadius:6,background:template.accent,color:template.style==="light"?"#fff":"#000",fontSize:10,fontWeight:800,letterSpacing:"0.04em"}}>{template.badge}</div>}<div style={{width:"100%",height:h,borderRadius:isTile?4:10,overflow:"hidden",position:"relative",background:C.surface}}>{imageUrl?<img src={imageUrl} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<div style={{width:"100%",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><ImageIcon size={isTile?14:28} color={C.dim}/></div>}{price&&!isTile&&<div style={{position:"absolute",bottom:10,right:10,background:template.accent,color:template.style==="light"?"#fff":"#000",padding:"8px 14px",borderRadius:10,fontSize:18,fontWeight:900,fontFamily:DISPLAY,boxShadow:"0 4px 12px rgba(0,0,0,0.3)"}}>£{price}</div>}</div>{!isTile&&<div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginTop:12,paddingTop:10,borderTop:`1px solid ${template.accent}25`}}><div><div style={{fontSize:14,fontWeight:800,color:template.textColor,fontFamily:DISPLAY}}>{productName||"Product Name"}</div>{storeName&&<div style={{fontSize:10,color:template.textColor,opacity:0.55,marginTop:2}}>📍 {storeName}</div>}</div><div style={{width:30,height:30,borderRadius:8,background:`${template.accent}20`,border:`1.5px solid ${template.accent}40`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:900,color:template.accent}}>RI</div></div>}{isTile&&<div style={{marginTop:4}}><div style={{fontSize:7,fontWeight:700,color:template.textColor,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{productName||"Product"}</div>{price&&<div style={{fontSize:6,fontWeight:800,color:template.accent}}>£{price}</div>}{storeName&&<div style={{fontSize:5,color:template.textColor,opacity:0.5}}>{storeName}</div>}</div>}</div>;}

// ═══ TEMPLATE TILE (Section 4.3 — realistic mini previews) ═════
function TemplateTile({template,selected,imageUrl,productName,price,storeName,onClick}){return<button onClick={onClick} style={{padding:0,border:selected?`2.5px solid ${C.purple}`:`2px solid ${C.border}`,borderRadius:14,overflow:"hidden",cursor:"pointer",background:"none",transition:"border-color 0.2s,transform 0.15s",transform:selected?"scale(1.03)":"scale(1)",width:"100%"}}><TemplatePreview imageUrl={imageUrl} productName={productName} price={price} template={template} storeName={storeName} size="tile"/><div style={{padding:"5px 6px",background:selected?C.purpleDim:C.surface,textAlign:"center"}}><div style={{fontSize:9,fontWeight:800,color:selected?C.purple:C.muted,textTransform:"uppercase",letterSpacing:"0.06em"}}>{template.name}</div></div></button>;}

// ═══ CREATE VIEW (Single Post) ══════════════════════════════════
function CreateView({post:existingPost,storeName,onSave,onBack}){
  const[step,setStep]=useState(1);const fileRef=useRef(null);
  const[imageUrl,setImageUrl]=useState(existingPost?.imageUrl||null);
  const[enhancedUrl,setEnhancedUrl]=useState(existingPost?.enhancedUrl||null);
  const[productName,setProductName]=useState(existingPost?.productName||"");
  const[price,setPrice]=useState(existingPost?.price||"");
  const[template,setTemplate]=useState(existingPost?.template||TEMPLATES[0]);
  const[style,setStyle]=useState(existingPost?.style||"new_arrival");
  const[caption,setCaption]=useState(existingPost?.caption||"");
  const[generating,setGenerating]=useState(false);
  const[showBranding,setShowBranding]=useState(existingPost?.showBranding!==false);

  const handleImage=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=async ev=>{const raw=ev.target.result;setImageUrl(raw);try{setEnhancedUrl(await enhanceImage(raw,price,storeName,template));}catch{setEnhancedUrl(raw);}};r.readAsDataURL(f);};
  useEffect(()=>{if(imageUrl&&price)enhanceImage(imageUrl,price,storeName,template).then(setEnhancedUrl).catch(()=>{});},[price,template]);

  const genCaption=async()=>{setGenerating(true);try{const res=await fetch("/api/generate-caption",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productName,price,storeName,style})});const data=await res.json();if(data.caption)setCaption(data.caption);else throw new Error();}catch{const tag=storeName?`#${storeName.replace(/\s/g,"").toLowerCase()}`:"#localshop";setCaption(`${productName}${price?` — just £${price}`:""} 🔥\n\nIn store NOW. You know where we are 👀\n\n#ConvenienceStore #Deals ${tag}`);}setGenerating(false);};

  const save=()=>onSave({id:existingPost?.id||`post_${Date.now()}`,imageUrl:enhancedUrl||imageUrl,rawImageUrl:imageUrl,enhancedUrl,productName,price,template,style,caption,showBranding,createdAt:existingPost?.createdAt||new Date().toISOString()});

  const steps=[{n:1,l:"Photo",i:<Camera size={11}/>},{n:2,l:"Template",i:<LayoutTemplate size={11}/>},{n:3,l:"Caption",i:<Type size={11}/>},{n:4,l:"Preview",i:<Eye size={11}/>}];
  const wc=caption.split(/\s+/).filter(Boolean).length;
  const img=enhancedUrl||imageUrl;

  return<div style={{minHeight:"100vh",background:C.bg,fontFamily:FONT,color:C.text}}>
    <div style={{padding:"14px 20px",borderBottom:`1px solid ${C.border}`,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:10}}><button onClick={onBack} style={{background:"none",border:"none",color:C.muted,cursor:"pointer",padding:4}}><ChevronLeft size={20}/></button><span style={{fontSize:15,fontWeight:700,color:C.white}}>{existingPost?"Edit Post":"Create Post"}</span></div>{step===4&&<Btn primary small onClick={save}><Check size={12}/> Save</Btn>}</div>
    <div style={{padding:"10px 20px",display:"flex",gap:2,justifyContent:"center",background:C.card,borderBottom:`1px solid ${C.border}`}}>{steps.map(s=><button key={s.n} onClick={()=>{if(s.n<=step)setStep(s.n);}} style={{display:"flex",alignItems:"center",gap:4,padding:"7px 16px",borderRadius:8,border:"none",background:step===s.n?C.purpleDim:"transparent",color:step===s.n?C.purple:step>s.n?C.green:C.dim,fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:FONT}}>{step>s.n?<Check size={10} strokeWidth={3}/>:s.i}<span>{s.l}</span></button>)}</div>
    <div style={{padding:20,maxWidth:500,margin:"0 auto"}}>
      {/* STEP 1 */}
      {step===1&&<div className="fade-up"><input ref={fileRef} type="file" accept="image/*" capture="environment" onChange={handleImage} style={{display:"none"}}/>{!imageUrl?<Card onClick={()=>fileRef.current?.click()} style={{textAlign:"center",padding:48,cursor:"pointer",border:`2px dashed ${C.borderLight}`,background:C.surface}}><div style={{width:72,height:72,borderRadius:18,margin:"0 auto 20px",background:C.purpleDim,display:"flex",alignItems:"center",justifyContent:"center"}}><Camera size={32} color={C.purple}/></div><div style={{fontSize:16,fontWeight:800,color:C.white,marginBottom:6,fontFamily:DISPLAY}}>Add a product photo</div><div style={{fontSize:12,color:C.dim,lineHeight:1.6}}>Take a snap or choose from your gallery.<br/>Auto-enhances to square 1080×1080.</div></Card>:<><Card style={{padding:0,overflow:"hidden",marginBottom:14}}><div style={{position:"relative"}}><img src={img} alt="" style={{width:"100%",maxHeight:280,objectFit:"cover",display:"block"}}/><button onClick={()=>{setImageUrl(null);setEnhancedUrl(null);}} style={{position:"absolute",top:10,right:10,width:32,height:32,borderRadius:8,background:"rgba(0,0,0,0.65)",border:"none",color:"#fff",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",backdropFilter:"blur(8px)"}}><X size={14}/></button><button onClick={()=>fileRef.current?.click()} style={{position:"absolute",top:10,left:10,padding:"6px 12px",borderRadius:8,background:"rgba(0,0,0,0.65)",border:"none",color:"#fff",cursor:"pointer",fontSize:11,fontWeight:600,fontFamily:FONT,display:"flex",alignItems:"center",gap:4,backdropFilter:"blur(8px)"}}><RefreshCw size={11}/> Change</button>{enhancedUrl&&<Badge color={C.green} style={{position:"absolute",bottom:10,left:10,fontSize:9}}><Sparkles size={9}/> Enhanced</Badge>}</div></Card><Card style={{marginBottom:14}}><SectionLabel>Product Details</SectionLabel><input value={productName} onChange={e=>setProductName(e.target.value)} placeholder="Product name (e.g. Coca-Cola 2L)" style={{width:"100%",padding:"13px 14px",borderRadius:10,background:C.surface,color:C.white,border:`1px solid ${C.border}`,fontSize:14,outline:"none",fontFamily:FONT,boxSizing:"border-box",marginBottom:8}}/><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Price — optional (e.g. 1.99)" style={{width:"100%",padding:"13px 14px",borderRadius:10,background:C.surface,color:C.white,border:`1px solid ${C.border}`,fontSize:14,outline:"none",fontFamily:FONT,boxSizing:"border-box"}}/></Card><Card style={{marginBottom:16}}><SectionLabel>Options</SectionLabel><Toggle value={showBranding} onChange={setShowBranding} label="Branded template frame"/></Card></>}{imageUrl&&productName&&<Btn primary onClick={()=>setStep(2)} style={{width:"100%",justifyContent:"center",padding:16,borderRadius:14}}>Next: Choose Template <ArrowRight size={14}/></Btn>}</div>}
      {/* STEP 2 */}
      {step===2&&<div className="fade-up"><SectionLabel style={{marginBottom:12}}>Choose a style</SectionLabel><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginBottom:20}}>{TEMPLATES.map(t=><TemplateTile key={t.id} template={t} selected={template.id===t.id} imageUrl={img} productName={productName} price={price} storeName={storeName} onClick={()=>setTemplate(t)}/>)}</div>{img&&<Card style={{marginBottom:18,padding:0,overflow:"hidden"}}><TemplatePreview imageUrl={img} productName={productName} price={price} template={template} storeName={storeName}/></Card>}<Btn primary onClick={()=>{setStep(3);if(!caption)genCaption();}} style={{width:"100%",justifyContent:"center",padding:16,borderRadius:14}}>Next: AI Caption <Sparkles size={14}/></Btn></div>}
      {/* STEP 3 */}
      {step===3&&<div className="fade-up"><SectionLabel style={{marginBottom:10}}>Caption style</SectionLabel><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,marginBottom:16}}>{CAPTION_STYLES.map(s=><button key={s.id} onClick={()=>setStyle(s.id)} style={{display:"flex",alignItems:"center",gap:10,padding:"11px 12px",borderRadius:12,cursor:"pointer",textAlign:"left",border:style===s.id?`1.5px solid ${C.purple}`:`1px solid ${C.border}`,background:style===s.id?C.purpleDim:C.surface,transition:"all 0.2s"}}><span style={{fontSize:18}}>{s.emoji}</span><div><div style={{fontSize:11,fontWeight:700,color:C.white}}>{s.label}</div><div style={{fontSize:9,color:C.dim}}>{s.best}</div></div></button>)}</div><div style={{display:"flex",gap:6,marginBottom:14}}><Btn onClick={genCaption} disabled={generating} style={{flex:1,justifyContent:"center",padding:14,borderRadius:12,background:C.purpleDim,color:C.purple,border:`1px solid ${C.purple}33`}}>{generating?<><RefreshCw size={14} style={{animation:"spin 1s linear infinite"}}/> Writing…</>:<><Wand2 size={14}/> {caption?"Regenerate":"Generate"}</>}</Btn>{caption&&<Btn onClick={()=>{const ss=CAPTION_STYLES.map(s=>s.id);const nx=ss[(ss.indexOf(style)+1)%ss.length];setStyle(nx);setTimeout(genCaption,100);}} disabled={generating} style={{padding:14,borderRadius:12}}><Shuffle size={14}/></Btn>}</div><div style={{position:"relative"}}><textarea value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Your AI caption will appear here — or write your own…" rows={8} style={{width:"100%",padding:16,borderRadius:14,background:C.surface,color:C.white,border:`1px solid ${C.border}`,fontSize:13,lineHeight:1.7,outline:"none",fontFamily:FONT,resize:"vertical",boxSizing:"border-box"}}/><div style={{position:"absolute",bottom:8,right:12,fontSize:10,color:wc>150?C.red:C.dim,fontWeight:600}}>{wc}/150 words</div></div>{caption&&<Btn primary onClick={()=>setStep(4)} style={{width:"100%",justifyContent:"center",padding:16,borderRadius:14,marginTop:14}}>Preview Post <Eye size={14}/></Btn>}</div>}
      {/* STEP 4 */}
      {step===4&&<PreviewStep imageUrl={img} productName={productName} price={price} template={template} caption={caption} storeName={storeName} onSave={save}/>}
    </div>
  </div>;
}

// ═══ PREVIEW STEP (Section 2.3 — honest FB copy) ════════════════
function PreviewStep({imageUrl,productName,price,template,caption,storeName,onSave}){const[copied,setCopied]=useState(false);const[opening,setOpening]=useState(false);return<div className="fade-up"><Card style={{padding:0,overflow:"hidden",marginBottom:16}}><div style={{padding:"14px 16px",display:"flex",alignItems:"center",gap:10}}><div style={{width:42,height:42,borderRadius:"50%",background:`linear-gradient(135deg,${C.purple},#7C3AED)`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:900,color:"#fff"}}>{(storeName||"S").slice(0,2).toUpperCase()}</div><div><div style={{fontSize:14,fontWeight:700,color:C.white}}>{storeName||"Your Store"}</div><div style={{fontSize:11,color:C.dim}}>Just now · 🌍</div></div></div><div style={{padding:"0 16px 14px",fontSize:13,color:C.text,lineHeight:1.65,whiteSpace:"pre-wrap"}}>{caption}</div><TemplatePreview imageUrl={imageUrl} productName={productName} price={price} template={template} storeName={storeName} size="large"/><div style={{padding:"10px 16px",borderTop:`1px solid ${C.border}`,display:"flex",justifyContent:"space-between"}}><span style={{fontSize:12,color:C.dim}}>👍 ❤️ 12</span><span style={{fontSize:12,color:C.dim}}>3 comments · 2 shares</span></div></Card><div style={{display:"flex",flexDirection:"column",gap:8}}><Btn primary onClick={()=>{navigator.clipboard.writeText(caption);setOpening(true);setTimeout(()=>{window.open("https://www.facebook.com","_blank");setOpening(false);},600);}} style={{width:"100%",justifyContent:"center",padding:16,borderRadius:14}}>{opening?<><Check size={14}/> Copied — opening Facebook…</>:<><ExternalLink size={14}/> Copy Caption & Open Facebook</>}</Btn><div style={{textAlign:"center",fontSize:11,color:C.dim,marginTop:-4,marginBottom:4}}>Your caption is copied — just paste it when Facebook opens.</div><Btn onClick={()=>{navigator.clipboard.writeText(caption);setCopied(true);setTimeout(()=>setCopied(false),2000);}} style={{width:"100%",justifyContent:"center",padding:14,borderRadius:12}}>{copied?<><Check size={14}/> Copied!</>:<><Copy size={14}/> Copy Caption Only</>}</Btn><Btn onClick={onSave} style={{width:"100%",justifyContent:"center",padding:14,borderRadius:12,background:C.greenDim,color:C.green,border:`1px solid ${C.green}33`}}><Check size={14}/> Save to Library</Btn></div></div>;}

// ═══ BATCH UPLOAD — "Plan My Week" (Section 5) ═════════════════
function BatchView({storeName,onSave,onBack}){
  const[step,setStep]=useState("upload");
  const[images,setImages]=useState([]);
  const[captions,setCaptions]=useState({});
  const[progress,setProgress]=useState(0);
  const[templates,setTemplates]=useState({});
  const[styles,setStyles]=useState({});
  const fileRef=useRef(null);

  const handleFiles=e=>{const files=Array.from(e.target.files||[]).slice(0,7);const promises=files.map((f,i)=>{const id=`batch_${Date.now()}_${i}`;return new Promise(resolve=>{const r=new FileReader();r.onload=ev=>resolve({id,rawUrl:ev.target.result,name:"",price:""});r.readAsDataURL(f);});});Promise.all(promises).then(imgs=>{setImages(imgs);setStep("name");});};

  const genAll=async()=>{setStep("generating");setProgress(0);const res={};for(let i=0;i<images.length;i++){const img=images[i];const sid=styles[img.id]||CAPTION_STYLES[i%CAPTION_STYLES.length].id;try{const r=await fetch("/api/generate-caption",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productName:img.name,price:img.price,storeName,style:sid})});const d=await r.json();res[img.id]=d.caption||fb(img,storeName);}catch{res[img.id]=fb(img,storeName);}setProgress(i+1);}setCaptions(res);const at={};images.forEach((img,i)=>{at[img.id]=TEMPLATES[i%TEMPLATES.length];});setTemplates(at);const as={};images.forEach((img,i)=>{if(!styles[img.id])as[img.id]=CAPTION_STYLES[i%CAPTION_STYLES.length].id;});setStyles(prev=>({...as,...prev}));setStep("review");};

  const saveAll=async()=>{const newPosts=[];for(const img of images){const tmpl=templates[img.id]||TEMPLATES[0];let enh;try{enh=await enhanceImage(img.rawUrl,img.price,storeName,tmpl);}catch{enh=img.rawUrl;}newPosts.push({id:img.id,imageUrl:enh,rawImageUrl:img.rawUrl,enhancedUrl:enh,productName:img.name,price:img.price,template:tmpl,style:styles[img.id]||"new_arrival",caption:captions[img.id]||"",showBranding:true,createdAt:new Date().toISOString()});}const sched=autoSchedule(newPosts);onSave(newPosts,sched);};

  return<div style={{minHeight:"100vh",background:C.bg,fontFamily:FONT,color:C.text}}>
    <div style={{padding:"14px 20px",borderBottom:`1px solid ${C.border}`,display:"flex",alignItems:"center",gap:10}}><button onClick={onBack} style={{background:"none",border:"none",color:C.muted,cursor:"pointer",padding:4}}><ChevronLeft size={20}/></button><div><div style={{fontSize:15,fontWeight:700,color:C.white}}>Plan My Week</div><div style={{fontSize:11,color:C.dim}}>Upload up to 7 products — one for each day</div></div></div>
    <div style={{padding:20,maxWidth:500,margin:"0 auto"}}>
      {step==="upload"&&<div className="fade-up"><input ref={fileRef} type="file" accept="image/*" multiple onChange={handleFiles} style={{display:"none"}}/><Card onClick={()=>fileRef.current?.click()} style={{textAlign:"center",padding:48,cursor:"pointer",border:`2px dashed ${C.borderLight}`,background:C.surface}}><div style={{width:72,height:72,borderRadius:18,margin:"0 auto 20px",background:C.purpleDim,display:"flex",alignItems:"center",justifyContent:"center"}}><Upload size={32} color={C.purple}/></div><div style={{fontSize:16,fontWeight:800,color:C.white,marginBottom:6,fontFamily:DISPLAY}}>Select your products</div><div style={{fontSize:12,color:C.dim,lineHeight:1.6}}>Choose up to 7 photos from your gallery.<br/>One post per day, sorted for you.</div></Card></div>}
      {step==="name"&&<div className="fade-up"><SectionLabel>Name your products</SectionLabel><div style={{display:"flex",flexDirection:"column",gap:10,marginBottom:16}}>{images.map((img,i)=><Card key={img.id} style={{padding:12,display:"flex",gap:12,alignItems:"center"}}><img src={img.rawUrl} alt="" style={{width:56,height:56,borderRadius:8,objectFit:"cover",flexShrink:0}}/><div style={{flex:1}}><input value={img.name} onChange={e=>{const n=[...images];n[i]={...img,name:e.target.value};setImages(n);}} placeholder="Product name" style={{width:"100%",padding:"8px 10px",borderRadius:8,background:C.surface,color:C.white,border:`1px solid ${C.border}`,fontSize:13,outline:"none",fontFamily:FONT,boxSizing:"border-box",marginBottom:4}}/><input value={img.price} onChange={e=>{const n=[...images];n[i]={...img,price:e.target.value};setImages(n);}} placeholder="Price (optional)" style={{width:"100%",padding:"8px 10px",borderRadius:8,background:C.surface,color:C.white,border:`1px solid ${C.border}`,fontSize:12,outline:"none",fontFamily:FONT,boxSizing:"border-box"}}/></div><button onClick={()=>setImages(prev=>prev.filter(p=>p.id!==img.id))} style={{background:"none",border:"none",color:C.dim,cursor:"pointer",padding:4}}><X size={14}/></button></Card>)}</div><Btn primary onClick={genAll} disabled={images.some(i=>!i.name.trim())} style={{width:"100%",justifyContent:"center",padding:16,borderRadius:14}}><Wand2 size={14}/> Generate My Week</Btn></div>}
      {step==="generating"&&<div className="fade-up" style={{textAlign:"center",padding:"60px 0"}}><div style={{width:64,height:64,borderRadius:16,margin:"0 auto 20px",background:C.purpleDim,display:"flex",alignItems:"center",justifyContent:"center"}}><RefreshCw size={28} color={C.purple} style={{animation:"spin 1.5s linear infinite"}}/></div><div style={{fontSize:16,fontWeight:800,color:C.white,marginBottom:8,fontFamily:DISPLAY}}>Writing your week…</div><div style={{fontSize:13,color:C.dim,marginBottom:20}}>{progress} of {images.length} captions done</div><div style={{width:"100%",height:6,borderRadius:3,background:C.surface,overflow:"hidden"}}><div style={{height:"100%",borderRadius:3,background:C.purple,transition:"width 0.4s",width:`${(progress/images.length)*100}%`}}/></div></div>}
      {step==="review"&&<div className="fade-up"><SectionLabel>Review your week</SectionLabel><div style={{display:"flex",flexDirection:"column",gap:10,marginBottom:16}}>{images.map((img,i)=>{const dayIdx=PREFERRED_DAYS[i%7];return<Card key={img.id} style={{padding:12}}><div style={{display:"flex",gap:10,marginBottom:8,alignItems:"center"}}><img src={img.rawUrl} alt="" style={{width:48,height:48,borderRadius:8,objectFit:"cover"}}/><div style={{flex:1}}><div style={{fontSize:13,fontWeight:700,color:C.white}}>{img.name}</div><div style={{fontSize:10,color:C.dim}}>{DAYS_FULL[dayIdx]} at {POSTING_TIMES[dayIdx]}</div></div><Badge color={C.purple} style={{fontSize:8}}>{DAYS_SHORT[dayIdx]}</Badge></div><textarea value={captions[img.id]||""} onChange={e=>setCaptions(prev=>({...prev,[img.id]:e.target.value}))} rows={3} style={{width:"100%",padding:10,borderRadius:8,background:C.surface,color:C.text,border:`1px solid ${C.border}`,fontSize:11,lineHeight:1.6,outline:"none",fontFamily:FONT,resize:"vertical",boxSizing:"border-box"}}/></Card>;})}</div><Btn primary onClick={saveAll} style={{width:"100%",justifyContent:"center",padding:18,borderRadius:14,fontSize:15}}><Check size={16}/> Your week is ready ✅ — Save all posts</Btn></div>}
    </div>
  </div>;
}
function fb(img,storeName){const tag=storeName?`#${storeName.replace(/\s/g,"").toLowerCase()}`:"#localshop";return`${img.name}${img.price?` — just £${img.price}`:""} 🔥\n\nIn store NOW. Pop in and grab yours 👀\n\n#ConvenienceStore #Deals ${tag}`;}

// ═══ SCHEDULE VIEW (Section 5.3 — redesigned) ══════════════════
function ScheduleView({posts,schedule,onUpdate,onBack,showToast}){
  const[assigning,setAssigning]=useState(null);const sIds=Object.values(schedule).flat();const unsch=posts.filter(p=>!sIds.includes(p.id));
  const assign=(d)=>{if(!assigning)return;const cur=schedule[d]||[];if(cur.includes(assigning.id))return;onUpdate({...schedule,[d]:[...cur,assigning.id]});setAssigning(null);};
  const remove=(d,pid)=>onUpdate({...schedule,[d]:(schedule[d]||[]).filter(id=>id!==pid)});
  const autoArr=()=>{onUpdate(autoSchedule(posts));showToast("Auto-arranged ✅");};

  return<div style={{minHeight:"100vh",background:C.bg,fontFamily:FONT,color:C.text}}>
    <div style={{padding:"14px 20px",borderBottom:`1px solid ${C.border}`,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:10}}><button onClick={onBack} style={{background:"none",border:"none",color:C.muted,cursor:"pointer",padding:4}}><ChevronLeft size={20}/></button><div><div style={{fontSize:15,fontWeight:700,color:C.white}}>Weekly Schedule</div><div style={{fontSize:11,color:C.dim}}>Tap a post, then tap a day to assign</div></div></div><Btn small onClick={autoArr} style={{background:C.purpleDim,color:C.purple,border:`1px solid ${C.purple}33`}}><Shuffle size={12}/> Auto-arrange</Btn></div>
    <div style={{padding:20,maxWidth:500,margin:"0 auto"}}>
      {assigning&&<div className="fade-in" style={{padding:"10px 14px",borderRadius:10,marginBottom:14,background:C.purpleDim,border:`1px solid ${C.purple}44`,display:"flex",alignItems:"center",justifyContent:"space-between"}}><span style={{fontSize:12,color:C.purple,fontWeight:700}}><Zap size={11} style={{verticalAlign:"middle"}}/> Assigning: {assigning.productName}</span><button onClick={()=>setAssigning(null)} style={{background:"none",border:"none",color:C.purple,cursor:"pointer"}}><X size={14}/></button></div>}
      <div style={{display:"flex",flexDirection:"column",gap:6,marginBottom:20}}>
        {DAYS_FULL.map((day,i)=>{const dp=(schedule[i]||[]).map(id=>posts.find(p=>p.id===id)).filter(Boolean);return<Card key={day} onClick={()=>assigning&&assign(i)} style={{padding:14,cursor:assigning?"pointer":"default",border:assigning?`1.5px solid ${C.purple}44`:`1px solid ${C.border}`}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:dp.length?8:0}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:13,fontWeight:700,color:C.white}}>{day}</span><span style={{fontSize:10,color:C.dim}}>{POSTING_TIMES[i]}</span></div><Badge color={dp.length?C.purple:C.dim} style={{fontSize:9}}>{dp.length} post{dp.length!==1?"s":""}</Badge></div>{dp.map(p=><div key={p.id} style={{display:"flex",alignItems:"center",gap:8,padding:"7px 8px",background:C.surface,borderRadius:8,marginBottom:4}}>{p.imageUrl&&<img src={p.imageUrl} alt="" style={{width:28,height:28,borderRadius:5,objectFit:"cover"}}/>}<span style={{fontSize:11,color:C.text,flex:1,fontWeight:500}}>{p.productName}</span><button onClick={e=>{e.stopPropagation();remove(i,p.id);}} style={{background:"none",border:"none",color:C.red,cursor:"pointer",padding:2,opacity:0.7}}><X size={12}/></button></div>)}{!dp.length&&!assigning&&<div style={{fontSize:11,color:C.dim,fontStyle:"italic"}}>Nothing posted {day} — tap to add a post</div>}{assigning&&!dp.find(p=>p.id===assigning.id)&&<div style={{fontSize:11,color:C.purple,fontWeight:700,marginTop:4}}>+ Tap to assign here</div>}</Card>;})}
      </div>
      {unsch.length>0&&<Card><SectionLabel icon={<Layers size={11} color={C.amber}/>}>Unscheduled ({unsch.length})</SectionLabel><div style={{display:"flex",flexDirection:"column",gap:6}}>{unsch.map(p=><button key={p.id} onClick={()=>setAssigning(p)} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 12px",background:assigning?.id===p.id?C.purpleDim:C.surface,border:assigning?.id===p.id?`1.5px solid ${C.purple}`:`1px solid ${C.border}`,borderRadius:10,cursor:"pointer",width:"100%",textAlign:"left",transition:"all 0.2s"}}>{p.imageUrl&&<img src={p.imageUrl} alt="" style={{width:36,height:36,borderRadius:8,objectFit:"cover"}}/>}<div style={{flex:1}}><div style={{fontSize:12,fontWeight:700,color:C.white}}>{p.productName}</div><div style={{fontSize:10,color:C.dim}}>{CAPTION_STYLES.find(s=>s.id===p.style)?.label||"—"} · {p.template?.name}</div></div><ArrowRight size={12} color={C.purple}/></button>)}</div></Card>}
      {posts.length===0&&<Card style={{textAlign:"center",padding:32}}><div style={{fontSize:12,color:C.dim}}>Create some posts first, then come back to schedule them.</div></Card>}
    </div>
  </div>;
}
